
export const CHECKLIST_ITEMS = [
    { key: 'noticeToProceed', label: 'A. Notice to Proceed' },
    { key: 'biddersTechFinancialProposals', label: 'L. Bidders Technical and Financial Proposals' },
    { key: 'contractOfAgreement', label: 'B. Contract of Agreement' },
    { key: 'minutesPreBid', label: 'M. Minutes of Pre-Bid Conference' },
    { key: 'noticeOfAward', label: 'C. Notice of Award' },
    { key: 'biddingDocuments', label: 'N. Bidding Documents' },
    { key: 'bacResolutionAward', label: 'D. BAC Resolution to Award' },
    { key: 'inviteObservers', label: 'O.1. Letter Invitation to Observers' },
    { key: 'postQualReport', label: 'E. Post-Qual Evaulation Report' },
    { key: 'officialReceipt', label: 'O.2. Official Receipt' },
    { key: 'noticePostQual', label: 'F. Notice of Post-qualification' },
    { key: 'boardResolution', label: 'O.3. Board Resolution' },
    { key: 'bacResolutionPostQual', label: 'G. BAC Resolution to Post-qualify' },
    { key: 'philgepsAwardNotice', label: 'O.4. PhilGEPS Award Notice Abstract' },
    { key: 'abstractBidsEvaluated', label: 'H. Abstract of Bids as Evaluated' },
    { key: 'philgepsPosting', label: 'P.1. PhilGEPS Posting' },
    { key: 'twgBidEvalReport', label: 'I. TWG Bid Evaluation Report' },
    { key: 'websitePosting', label: 'P.2. Website Posting' },
    { key: 'minutesBidOpening', label: 'J. Minutes of Bid Opening' },
    { key: 'postingCertificate', label: 'P.3. Posting Certificate' },
    { key: 'resultEligibilityCheck', label: 'K. Eligibility Check Results' },
    { key: 'fundsAvailability', label: 'Q. CAF, PR, TOR & APP' },
];
